name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ['trigger_master_newTag']
    types:
      - completed

permissions:
  contents: read
  id-token: write

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.AR_SA_KEY }}

      - name: Configure Docker for Google Artifact Registry
        run: |
          gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev

      - name: Set environment variables for Docker
        run: |
          TAG=$(date +%Y%m%d%H%M%S)
          echo "ARTIFACT_IMAGE_TAG=$TAG" >> $GITHUB_ENV
          echo "ARTIFACT_IMAGE_PATH=${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REPO }}/Go_vocabs_be" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t $ARTIFACT_IMAGE_PATH:$ARTIFACT_IMAGE_TAG .
      
      - name: Push Docker image to Artifact Registry
        run: |
          docker push $ARTIFACT_IMAGE_PATH:$ARTIFACT_IMAGE_TAG

      - name: Notify Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          IMAGE_TAG: ${{ env.ARTIFACT_IMAGE_TAG }}
        run: |
          MESSAGE="New Docker image pushed: $IMAGE_TAG"
          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
          -d "chat_id=$TELEGRAM_CHAT_ID" \
          -d "text=$MESSAGE"
