name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Run Release Please
        id: release
        uses: googleapis/release-please-action@v2  # Sử dụng action mới
        with:
          release-type: simple
          token: ${{ secrets.GITHUB_TOKEN }}

  notify-telegram:
    runs-on: ubuntu-latest
    needs: release
    if: ${{ needs.release.outputs.releases_created == 'true' }}
    steps:
      - name: Send Telegram Notification
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          RELEASE_VERSION: ${{ needs.release.outputs.tag_name }}
        run: |
          MESSAGE="New Release Created: $RELEASE_VERSION"
          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
          -d "chat_id=$TELEGRAM_CHAT_ID" \
          -d "text=$MESSAGE"


# git commit -m "feat/fix/feat!: ..."

#curl -X POST "https://api.telegram.org/bot7576486969:AAFfEzcfi8YVMi0cerVmkF0pBXBbrMiAGE8/sendMessage" -d "chat_id=-1002322091777" -d "parse_mode=HTML" -d "text=<b>🚀 Đơn hàng mới 🚀</b> Mã đơn hàng: <b>123123123</b> Số điện thoại: <a href='tel:0938005053'><b>0938005053</b></a>"


